- accounts.go
- accounts_test.go
- go.mod
- go.sum
- main.go
- models/account.go
- models/mongo/accounts.go
- validators/validators.go
models package handling database interaction
Get from mail or Id 
Create/Delete Account
Update name, email or hash
List all Users almost done
Account schema update, uuid is store as id instead of Mongo Object ID 
Validator fix in update request in nested structure id validation
> Accounts repository implementation using MongoDB 

- groups.go
- models/mongo/notes.go
- models/notes.go
- notes.go
- server.go
- validators/notes.go
Note basic implementation, containing Add and Remove note 
#42, #40 
Note Models and Validator, with Add and Remove request
> Add and Remove Note from Group 

- accounts_test.go
- go.mod
- go.sum
- groups_test.go
- invites.go
- invites_test.go
- models/invites.go
- models/memory/accounts.go
- models/memory/groups.go
- models/memory/invites.go
- models/memory/members.go
- models/memory/service.go
- models/mongo/invites.go
- server.go
- validators/invites.go
Basically implements invites for this sprint 
Fixes #29 
Fixes #30 
- [ENHANCEMENT] Mongo/Memory invites + model
- [ENHANCEMENT] Send/Accept/Deny/Get/List invites
- [ENHANCEMENT] Validators
- [ENHANCEMENT] Restructure and fixes unit testing
- [ENHANCEMENT] Invites unit testing
> Invites and accepting / denying them

- accounts.go
- groups.go
- models/models.go
- models/mongo/accounts.go
- models/mongo/groups.go
Update fix a few issues
- [BUGFIX]
Unwanted document Id behavior, while updating a group or an account, 
The groups and accounts update was returning an error when the document was already updated, fix this issue by returning and empty object when unchanged field after the update  
New model error for invalid arguments provided to DB call (empty field for example) 
- [DOCS]
- ...
> Fix update endpoint accounts and groups 

- accounts.go
get account return data even if the requested account does not belong to the user
> fix get account from email or ID

- models/mongo/notes.go
- models/notes.go
- notes.go
- validators/notes.go
List and Get GroupNotes
Fixes #43 
- [BUGFIX]
Lister les notes d'un groupe, ou les notes d'un auteur dans un groupe 
Afficher une note selon son ID dans le note service
- [DOCS]
- ...
> Get and List GroupNotes

- accounts.go
Remove restrictions to get accounts
- [ENHANCEMENT] Remove restrictions to get accounts
> Remove restrictions to get accounts

- accounts.go
- groups.go
- members.go
- models/memory/members.go
RemoveMemberFromGroup now update the next member to admin, if the old one left 
Update error handlings from validators and models
- [BUGFIX]
change role from auth (Admin, User) to plain string
- [DOCS]
- ...
> Fix removeMember

- groups.go
add role check before delating the group's user belong to
> feat: check if user is admin before deleting the group

- accounts.go
- communication/notes.go
- main.go
- server.go
Communicate with notes-service to create a workspace when an account is created and to call "OnAccountDelete" when an account is deleted.
Made it so you don't have to connect to the notes-service in dev builds and in general if srv.noteSevrice in `nil`
- [ENHANCEMENT] Call to account service endpoints
> Communication with notes-service

- .gitmodules
- accounts.go
- main.go
- server.go
Fix google auth secret not grep in env.
Fix redirect URI with dev and prod.
Some typo and placing of methods.
> Fix : Crash google auth secret

- accounts.go
- validators/accounts.go
Change the google authentication code with an access token in parameter 
Fixes #99
> Fix : Change logic of the AuthenticateGoogle

- accounts.go
- validators/accounts.go
> feat: update account validation

- accounts.go
> feat: fix is account validate with gogole

- models/mongo/accounts.go
> fix: validate account created by google

- accounts.go
- accounts_test.go
- auth/service.go
- models/accounts.go
- models/mongo/accounts.go
> fix: authenticate accounts without hash no longer crash and unit test

- mails_content.go
> feat: improve goup invite mail

- accounts.go
- server.go
- validators/accounts.go
New endpoint, from code to access token
- Updated the google client redirect uri
> feat: GetAccessTokenGoogle

- accounts.go
> fix: auth google possible nil value unsafe

- mails_content.go
> feat: mail invite fix mail conte,t

- accounts.go
- models/mongo/accounts.go
> feat: clean code
